### ISSUE TITLE
/isedol/member 페이지에서 카드에 호버 효과가 제대로 일어나지 않음

### ISSUE THREAD

**Issue by So-chiru** [KoreaCodingKing/WakEnt#18]
원래 의도된 기능 동작은 현재 페이지에 카드가 일정 부분 보이면 그 카드에 호버 효과를 주도록 하는 것입니다. 
현재 작동하지 않는 겸 IntersectionObserver API를 사용하여 새로 작성하는 편이 나아 보입니다.

**Comment by KoreaCodingKing** [comment]
done
