### ISSUE TITLE
/isedol/member 페이지 이미지 로딩 해결

### ISSUE THREAD

**Issue by So-chiru** [KoreaCodingKing/WakEnt#21]
https://user-images.githubusercontent.com/32066651/152754776-3019f5b5-30f9-41ae-b833-690431e1b6f1.mov

이미지 로딩이 안되었을때 Alt Text가 보여지는 것이 퀄리티가 떨어져 보여서 나중에 페이지에 이미지 소스를 통째로 임베딩시키는 방식으로 해결하면 좋겠습니다.

**Comment by KoreaCodingKing** [comment]
현재 nextjs에서 제공하는 <Image>태그를 이용하고 있는데 <img>태그에 직접 src에 넣는다는 말씀이신거죠?
nextjs에서 Image태그를 사용하라고 하는데 문제생기지 않을까요?

**Comment by So-chiru** [comment]
> [](https://github.com/KoreaCodingKing/WakEnt/issues/21)[](https://github.com/KoreaCodingKing/WakEnt/issues/21)현재 nextjs에서 제공하는 태그를 이용하고 있는데 태그에 직접 src에 넣는다는 말씀이신거죠?

아뇨, 그냥 페이지 로드에서 전부 다 로드하게 하겠다는 소립니다
