### ISSUE TITLE
라이센스 표기 관련입니다.

### ISSUE THREAD

**Issue by So-chiru** [KoreaCodingKing/WakEnt#32]
MIT License로 등록하셨는데 제가 작성한 코드에 대해서는 공개를 원하지 않을 뿐더러 라이센스 표기에 제 이름도 올라가 있지 않네요.
제 코드를 전부 삭제해주시든 라이센스를 내려주시든 조치를 취하시기 바랍니다.

**Comment by KoreaCodingKing** [comment]
넵넵 라이센스 삭제하겠습니다
