### ISSUE TITLE
2022.10.23 이슈공유 및 제안

### ISSUE THREAD

**Issue by jkas2016** [KoreaCodingKing/WakEnt#36]
## 새 페이지 로드 시 자동재생
크롬 정책에 따라 2018년 4월부터 페이지가 새로 로드 될 때 mute 되지 않은 자동재생을 방지함 (modal 등 이미 페이지가 로드 된 상태에서 동적으로 동영상 플레이어를 띄울 때는 autoplay 옵션이 정상적으로 작동 됨)
https://developer.chrome.com/blog/autoplay/

대안: https://stackoverflow.com/questions/40685142/youtube-autoplay-does-not-work-with-iframe
이외에도 초기 mute 설정으로 동영상 재생한 뒤 sound on 버튼을 제공하여 동적으로 사운드를 제어하는 방식이 있을 것으로 생각 됨 (확인 필요)

## 유튜브 제목 제거
유튜브 정책의 변경으로 showinfo(제목, 유튜브 로고), rel(관련동영상) 동작 방식이 변경됨
https://developers.google.com/youtube/player_parameters#august-23,-2018
* showinfo : 무시 됨
* rel=0 : 관련 동영상이 표시 되지 않는 방식에서 해당 채널의 동영상이 표시되는 방식으로 변경 됨

굳이 방법을 찾자면 다음과 같은 방법이 있음
대체 : [제목을 없애는 방법(HTML/CSS)](https://studiomx.co.kr/4645/%EC%9C%A0%ED%8A%9C%EB%B8%8C-iframe-%EB%8F%99%EC%98%81%EC%83%81-%EC%B6%94%EA%B0%80%EC%8B%9C-%EC%82%AC%EC%9A%A9-%EA%B0%80%EB%8A%A5%ED%95%9C-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98/)

## Library 사용 제안 (검토요청)

[iframe 삽입에 대한 YouTube Player API 참조 문서](https://developers.google.com/youtube/iframe_api_reference#Requirements) 에서 소개되는 API에 대한 간단한 인터페이스 제공
https://github.com/tjallingt/react-youtube

**Comment by jkas2016** [comment]
자동 재생 관련 이슈는 공식 API 를 통해 해결 할 수 있을 듯 보입니다. (동영상 로드 완료 시 재생 API 실행)
https://developers.google.com/youtube/iframe_api_reference#Events

**Comment by KoreaCodingKing** [comment]
영상의 소리는 안나와도 되어 자동재생에는 큰 문제가 없어보입니다.
muted로 설정하시고 작업하시면 될듯합니다.

자동재생및 iframe태그내의 유튜브 온로드나 재생완료시 이벤트 처리(동영상 로드 완료, 동영상 완료시 state변경 등)는
https://developers.google.com/youtube/iframe_api_reference
여기서 확인하면 되는데
개발 편의를 위해서 라이브러리를 사용하신다면 이용하셔도 상관이 없습니다!

**Comment by KoreaCodingKing** [comment]
그 첫 입장시 영상에는 이런방식을 고려하면 되지만
모달창에서 유튭 영상을 보여주는거는 따로 완성된 컴포넌트가 있기에 그거를 이용하시면 됩니다!
YouTubePlayerOverlay 컴포넌트 참고

**Comment by jkas2016** [comment]
@KoreaCodingKing 님

1. 자동재생 : 확인 감사합니다 걱정 없겠네요
2. YouTubePlayerOverlay 는 확인했습니다 감사합니다.
3. 유튜브 제목 제거 부분도 인지 하셨을까요? 같이 대안 리서치 해주시면 감사하겠습니다

**Comment by KoreaCodingKing** [comment]
일단 저도 찾아보면서 쓸만한 controls 값들을 정리했습니다.
https://developers.google.com/youtube/player_parameters#controls

controls: 이 매개변수는 동영상 플레이어 컨트롤을 표시할지 여부를 나타냅니다.
  controls=0 – 플레이어 컨트롤이 플레이어에 표시되지 않습니다.
  controls=1(기본값) – 플레이어 컨트롤이 플레이어에 표시됩니다.

modestbranding: 이 매개변수를 통해 YouTube 로고를 표시하지 않는 YouTube 플레이어를 사용할 수 있습니다. 매개변수 값을 1로 설정하면 YouTube 로고가 컨트롤바에 표시되지 않습니다. 하지만 사용자가 마우스 포인터를 플레이어 위에 올려놓으면 작은 YouTube 텍스트 라벨이 일시중지된 동영상의 오른쪽 상단에 표시됩니다.

disablekb: 매개변수 값을 1으로 설정하면 플레이어가 키보드 컨트롤에 응답하지 않습니다. 기본값은 0이며 이 값을 사용하면 키보드 컨트롤이 사용 설정됩니다.

fs: 이 매개변수를 0으로 설정하면 전체 화면 버튼이 플레이어에 표시되지 않습니다. 기본값은 1이며 이 값을 사용하면 전체 화면 버튼이 표시됩니다.

rel: 참고: 이 매개변수는 2018년 9월 25일 이후에 [변경](https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018)됩니다.

변경 전까지 이 매개변수는 초기 동영상의 재생이 종료될 때 플레이어에서 관련 동영상을 표시할지 여부를 나타냅니다.
매개변수 값을 기본값인 1로 설정하면 플레이어에 관련 동영상이 표시됩니다.
매개변수 값을 0으로 설정하면 플레이어에 관련 동영상이 표시되지 않습니다.
변경 후에는 관련 동영상을 사용 중지할 수 없게 됩니다. 대신 rel 매개변수를 0으로 설정하면 방금 동영상이 재생된 채널에서 관련 동영상을 가져옵니다
-> 이거는 동영상 끝나기전 로딩화면 state를 false로 처리하면 좋을 듯 싶습니다.

cc_lang_pref: 이 매개변수를 사용하고 [cc_load_policy](https://developers.google.com/youtube/player_parameters#cc_load_policy) 매개변수를 1로 설정하면 플레이어가 로드될 때 플레이어에 지정된 언어로 자막이 표시됩니다. [cc_load_policy](https://developers.google.com/youtube/player_parameters#cc_load_policy) 매개변수를 설정하지 않으면 기본적으로 자막이 표시되지 않습니다. 그러나 사용자가 자막을 사용하도록 선택하면 지정된 언어로 자막이 표시됩니다.



유튜브 제목은 유튜브 정책으로 막혔다는 소리도 있고 하는데....
https://ezio.tistory.com/427
showinfo를 0으로 설정하면 된다네요...뭐가 맞는건지

아니면 다른 방법으로
iframe 위에 div 커버 하나 만들어서 iframe에 마우스 오버해도 indicate 되지 않게 하는 방법은 어떨까요...?

간단할 줄 알았던 문제가 이렇게 클줄 몰랐네요...제가 맡을껄...

**Comment by KoreaCodingKing** [comment]
이슈가 아직 완벽하게 끝난 부분이 아니라 해결전까진 이슈 오픈 해 두겠습니다.

**Comment by KoreaCodingKing** [comment]
메인페이지 영상 스토리지 구매로 해결
라이브러리 사용 완.

이슈 해결로 닫겠습니다!
