### ISSUE TITLE
Display: grid; 사용 시 중앙부터 채우기

### ISSUE THREAD

**Issue by jkas2016** [KoreaCodingKing/WakEnt#42]
tsx 코드 위치
https://github.com/KoreaCodingKing/WakEnt/blob/feature/discography/components/ldc/Discography/index.tsx

style 코드 위치 
https://github.com/KoreaCodingKing/WakEnt/blob/feature/discography/styles/pages/Ldc/Discography/index.module.scss#L71

@KoreaCodingKing 님
현재 아래 스크린샷 처럼 노출되는 상황인데 
새로운 row에 item 채워질 때 가운데부터 채워지게 하려면 어떤 방법이 있을 까요? 
리서치 하는 중인데 잘 안찾아져서 문의드립니다 (__)
이미 경험해보신 사례가 아닐까해서...
![FireShot Capture 003 -  - localhost](https://user-images.githubusercontent.com/21357981/201522698-bfa9f397-b5c7-49d3-9815-3ee16f318931.png)

**Comment by KoreaCodingKing** [comment]
음... justify contents: center로 해보시거나
center 속성을 갖는 속성들이 있습니다. 위에께 안되면 align-self나 해보시면 될것 같습니다.

**Comment by jkas2016** [comment]
@KoreaCodingKing 님 

감사합니다~
display: flex 로 변경해서 작업 했습니다

**Comment by KoreaCodingKing** [comment]
좋습니다!👍
